name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bugs Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Development'
    labels:
      - 'chore'
change-template: '- #$NUMBER $TITLE'
change-title-escapes: '\<*_&`#@'
template: |
  $CHANGES

  Thanks to $CONTRIBUTORS
