packageExtensions:
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint-config-airbnb-base: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
