name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: cat .yarnrc_patch.yml >> .yarnrc.yml
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn docs
      # - name: Deploy
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
      #     enable_jekyll: false
